export const categoriesData = [
    { id: 1, name: 'Electronics', slug: 'electronics' },
    { id: 2, name: 'Fashion', slug: 'fashion' },
    { id: 3, name: 'Home & Kitchen', slug: 'home' },
    { id: 4, name: 'Health & Beauty', slug: 'health' },
    { id: 5, name: 'Toys & Games', slug: 'games' },
    { id: 6, name: 'Sports & Outdoors', slug: 'sports' },
    { id: 7, name: 'Books', slug: 'books' },
    { id: 8, name: 'Automotive', slug: 'automotive' },
    { id: 9, name: 'Grocery', slug: 'grocery' },
    { id: 10, name: 'Pet Supplies', slug: 'pets' },
    { id: 11, name: 'Tools & Home Improvement', slug: 'tools' },
    { id: 12, name: 'Baby', slug: 'baby' },
    { id: 13, name: 'Handmade', slug: 'handmade' },
    { id: 14, name: 'Software', slug: 'software' },
  ];


export const products = [
    {
        "id": 1,
        "title": "Bluetooth Earbuds",
        "category": "Electronics",
        "sub_category": "Audio",
        "location": "Lagos, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "new",
        "price": 49.99,
        "negotiable": true,
        "phone_number": "123-456-7890",
        "max_delivery_charge": 5.00,
        "min_delivery_charge": 2.50
    },
    {
        "id": 2,
        "title": "Leather Wallet",
        "category": "Fashion",
        "sub_category": "Accessories",
        "location": "Abuja, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "new",
        "price": 29.99,
        "negotiable": false,
        "phone_number": "456-789-0123",
        "max_delivery_charge": 7.00,
        "min_delivery_charge": 3.00
    },
    {
        "id": 3,
        "title": "Tracker Watch",
        "category": "Electronics",
        "sub_category": "Fitness",
        "location": "Kano, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "used",
        "price": 39.99,
        "negotiable": true,
        "phone_number": "789-012-3456",
        "max_delivery_charge": 6.00,
        "min_delivery_charge": 2.00
    },
    {
        "id": 4,
        "title": "Steel Water Bottle",
        "category": "Home",
        "sub_category": "Kitchenware",
        "location": "Ibadan, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "new",
        "price": 19.99,
        "negotiable": true,
        "phone_number": "012-345-6789",
        "max_delivery_charge": 8.00,
        "min_delivery_charge": 4.00
    },
    {
        "id": 5,
        "title": "Vintage Record Player",
        "category": "Electronics",
        "sub_category": "Audio",
        "location": "Kaduna, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "used",
        "price": 99.99,
        "negotiable": true,
        "phone_number": "234-567-8901",
        "max_delivery_charge": 10.00,
        "min_delivery_charge": 5.00
    },
    {
        "id": 6,
        "title": "Running Shoes",
        "category": "Fashion",
        "sub_category": "Footwear",
        "location": "Adamawa, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "new",
        "price": 59.99,
        "negotiable": false,
        "phone_number": "567-890-1234",
        "max_delivery_charge": 6.50,
        "min_delivery_charge": 3.50
    },
    {
        "id": 7,
        "title": "Camera",
        "category": "Electronics",
        "sub_category": "Photography",
        "location": "Jos, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "used",
        "price": 199.99,
        "negotiable": true,
        "phone_number": "890-123-4567",
        "max_delivery_charge": 12.00,
        "min_delivery_charge": 6.00
    },
    {
        "id": 8,
        "title": "Smartphone",
        "category": "Electronics",
        "sub_category": "Mobile Phones",
        "location": "Aba, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "used",
        "price": 299.99,
        "negotiable": true,
        "phone_number": "345-678-9012",
        "max_delivery_charge": 15.00,
        "min_delivery_charge": 8.00
    },
    {
        "id": 9,
        "title": "Knife Set",
        "category": "Home",
        "sub_category": "Cookware",
        "location": "Owerri, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "new",
        "price": 79.99,
        "negotiable": true,
        "phone_number": "678-901-2345",
        "max_delivery_charge": 8.00,
        "min_delivery_charge": 4.00
    },
    {
        "id": 10,
        "title": "Dress Shirt",
        "category": "Fashion",
        "sub_category": "Clothing",
        "location": "Enugu, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "new",
        "price": 39.99,
        "negotiable": false,
        "phone_number": "901-234-5678",
        "max_delivery_charge": 6.00,
        "min_delivery_charge": 3.00
    },
    {
        "id": 11,
        "title": "Speaker",
        "category": "Electronics",
        "sub_category": "Audio",
        "location": "Abeokuta, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "new",
        "price": 79.99,
        "negotiable": true,
        "phone_number": "123-456-7890",
        "max_delivery_charge": 8.00,
        "min_delivery_charge": 4.00
    },
    {
        "id": 12,
        "title": "Yoga Mat",
        "category": "Sports",
        "sub_category": "Fitness",
        "location": "Onitsha, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "used",
        "price": 19.99,
        "negotiable": true,
        "phone_number": "456-789-0123",
        "max_delivery_charge": 7.00,
        "min_delivery_charge": 3.50
    },
    {
        "id": 13,
        "title": "Laptop Backpack",
        "category": "Electronics",
        "sub_category": "Accessories",
        "location": "Warri, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "new",
        "price": 49.99,
        "negotiable": false,
        "phone_number": "789-012-3456",
        "max_delivery_charge": 6.50,
        "min_delivery_charge": 3.00
    },
    {
        "id": 14,
        "title": "Toy Set",
        "category": "Toys",
        "sub_category": "Educational",
        "location": "Calabar, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "new",
        "price": 29.99,
        "negotiable": true,
        "phone_number": "012-345-6789",
        "max_delivery_charge": 10.00,
        "min_delivery_charge": 5.00
    },
    {
        "id": 15,
        "title": "Charging Pad",
        "category": "Electronics",
        "sub_category": "Mobile",
        "location": "Benin City, Nigeria",
        "photo": "https://dummyimage.com/300x200",
        "condition": "new",
        "price": 19.99,
        "negotiable": true,
        "phone_number": "234-567-8901",
        "max_delivery_charge": 5.00,
        "min_delivery_charge": 2.50
    }
]